services:
  main-db:
    image: postgres:17
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: ${MAIN_DB_USER}
      POSTGRES_PASSWORD: ${MAIN_DB_PASSWORD}
      POSTGRES_DB: ${MAIN_DB_DATABASE}
    env_file:
      - .env
    volumes:
      - main-db-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${MAIN_DB_USER} -d ${MAIN_DB_DATABASE}"]
      interval: 10s
      timeout: 5s
      retries: 5

  analytic-db:
    image: postgres:17
    ports:
      - 5433:5432
    environment:
      POSTGRES_USER: ${ANALYTIC_DB_USER}
      POSTGRES_PASSWORD: ${ANALYTIC_DB_PASSWORD}
      POSTGRES_DB: ${ANALYTIC_DB_DATABASE}
    env_file:
      - .env
    volumes:
      - analytic-db-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${ANALYTIC_DB_USER} -d ${ANALYTIC_DB_DATABASE}"]
      interval: 10s
      timeout: 5s
      retries: 5  

  redis:
    image: redis:latest
    ports:
      - 6379:6379
    volumes:
      - redis-data:/data
    healthcheck:
      test: ["CMD-SHELL", "redis-cli ping"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  main-db-data:
  analytic-db-data:
  redis-data: